name = "Text-MustacheTemplate"
badges = ["github-actions/test.yml", "metacpan"]
module_maker="ModuleBuild"
static_install = "auto"
markdown_maker = "Pod::Markdown::Github"

[Metadata]
x_static_install = 1